### ISSUE TITLE
[Bugs] Guava test suits.

### ISSUE THREAD

**Issue by Speiger** [Speiger/Primitive-Collections#1]
After finding @ben-manes FastUtil test suit using Guavas Test Library.
I ran my library through the same tests and found loads of bugs... (56 in the example that was provided to FastUtil)

So the goal is now to address these bugs before the next update and implement even more Test-cases.

Tests that need to be done and completed:
- [x] Maps
   - [x] HashMap,
   - [x] LinkedHashMap
   - [x] CustomHashMap
   - [x] LinkedCustomHashMap
   - [X] ImmutableHashMap
   - [x] ArrayMap
   - [x] EnumMap
   - [x] LinkedEnumMap
   - [x] RBTreeMap
   - [x] AVLTreeMap
   - [x] SortedMap
   - [x] NavigableMap

- [x] Lists:
   - [x] ArrayList
   - [x] LinkedList
   - [x] ImmutableList

- [x] Sets
   - [x] HashSet
   - [x] LinkedHashSet
   - [x] CustomHashSet
   - [x] LinkedCustomHashSet
   - [x] ImmutableHashSet
   - [x] ArraySet
   - [x] RBTreeSet
   - [x] AVLTreeSet
   - [x] SortedSet
   - [x] NavigableSet

Thanks @ben-manes for bringing that to the attention.
I know I kinda leach of fastutils work here but If you are willing I would love to add even more testsuits to my library to reduce bugs.

**Comment by ben-manes** [comment]
Oh that's wonderful! Whenever I'm curious and run it against a library I've found bugs. That includes my own back in the day! It's a great suite that was only evangelized in the earliest days of Google Collections (pre-Guava). I'd recommend writing primitive generators in the theme of `TestStringMapGenerator` and friends, so that you can get coverage on non-object collections.

My only ask is that you share any test goodies back to others, such as FastUtil, so they can benefit. I did this when running against other caches which were buggy. That's not really about helping out a competing project but rather the innocent users who might be impacted.

You are very welcome to scavenge from [Caffeine](https://github.com/ben-manes/caffeine) for tests. I wrote my own tests, pulled in others (jsr tcks, guava), every static analyzer that I could find, reviewed Commons etc for test cases, and still bugs crop up. In my case I pushed the testing framework far via millions of permutations to brute force coverage, since CI compute time is free for OSS (~2hr builds!). OpenJDK's SIMD tests by [code generating](https://github.com/openjdk/jdk/blob/master/test/jdk/jdk/incubator/vector/templates/Unit-header.template) their type variants, which seems like an idea you could leverage here. Borrow liberally! 🙂

**Comment by Speiger** [comment]
Thank you for that.

Well my plan was to implement tests for every implementation and upload it to this github repo.
So everything would be open source and under the Apache2 license. (Same as FastUtil)
And everything would be automatically downloaded via the gradle wrapper thats needed.
So it would be plug and play no extra software required.
So it would be free for the taking. Does that satisfy your request?

Thank you for these extra infos I will dig into that once i am through the list of things to do which are much larger then this...
(The entire library will be tested through this at the very least)

**Comment by ben-manes** [comment]
definitely. You might also comment on the FastUtil issue simply to say that you implemented some test utilities, e.g. `TestIntMapGenerator`, that they are welcome to borrow from. Then it's modestly discoverable and hints to FastUtil that they could go a bit further then the sample test that I provided. Likely they won't either way, but it's the welcoming spirit of give-and-take in open source projects that makes it great.

and of course if you find anything that I could borrow back into making Caffeine better, please let me know 😄

**Comment by Speiger** [comment]
That is sadly not a possibility from my side.
Doe to difference and me being annoyed to a point where I didn't care about reputation anymore.
I was basically not at the best of my behavior, and that resulted basically in a ban.
Which was totally right, If roles were reversed I would have done it too.
The reason was mainly that FastUtil has so many essential issues and I was seeing no desire to address them at all, not even with external help, that I decided in the end I make my own.

I admit it wasn't my best moment out there. On the other hand I have now a library where I don't fall into pitfalls because of a less then good implementation outside the core Collections (HashMap, ArrayList). Which still isn't addressed a year or two after.

I am not even sure if they are aware of my Clone.
Except of keeping track of their issues to make sure they are address on my side to I don't really interact with them. 
I have no issues though if they want to look on my project and improve theirs through that. I just try to keep interactions as low as possible to reduce unnecessary fights over design choices.

But If you want to give them a shout out that they might have a cross reference they can work with I have no problems with that.

**Comment by ben-manes** [comment]
Fair enough. Thanks for the honest, introspection, and not taking offense if your work is mentioned for them to consider borrow from.

**Comment by Speiger** [comment]
This whole library is basically the manifestation of the want to improve FastUtil and being denied of doing so.

**Comment by ben-manes** [comment]
Oh, and guava has more than just map test suite builders so your todo list might be much longer!

**Comment by Speiger** [comment]
Phew this was a Endurance test... And I am not even done because some implementations require entire rewirtes to get them fixed.
(SubMaps & SubSets of Array/Tree Maps/Sets)

But yeah there are now 16k tests thanks to you in this library.
And I did some basic math and guessing but if I add all possible mutations into testing. Eh yeah this is going to get at least half a million tests maybe even more then a million tests...

Seriously @ben-manes thanks to your issue report i was able to squash thousands of small bugs that were in my library.
(A good chunk of them are in FastUtil too... maybe more)
@vigna if you want to have a look for a simple and quick java8 implementation of these tests
[[List Tests]](https://github.com/Speiger/Primitive-Collections/blob/master/src/test/java/speiger/src/collections/objects/list/ObjectListTests.java) [[Map Tests]](https://github.com/Speiger/Primitive-Collections/blob/master/src/test/java/speiger/src/collections/objects/map/ObjectMapTests.java)  [[Set Tests]](https://github.com/Speiger/Primitive-Collections/blob/master/src/test/java/speiger/src/collections/objects/set/ObjectSetTests.java)

**Comment by Speiger** [comment]
@ben-manes closing this issue because the basic unit test framework is now implemented and will be slowly expanded.

Just to added a summary.
- Added: 160k Unit tests for 1 permutation. (Most comes from TreeMaps since Navigable Maps have loads of tests)
- Fixed: Thousands of bugs that were present not only in my but FastUtils implementation.
- Trivia: Spend 3-4 days the moment i found out about it and its done.
- Trivia: Estimated Unit tests that will appear for all premutations: 10 Million....

Though FastUtils percentage of bugs might be a lot lower then mine since roughly half of the bugs came of implementations that were still missing in FastUtil.

@vigna if you want to take a look and reduce the work required to improve FastUtil, you are invited.

again thank you @ben-manes. Thanks to you I was able to stabilize and improve the quality of Primitive Collections by a HUGE margin.

**Comment by ben-manes** [comment]
I saw your reddit comment,
> But I had issues getting JMH running with gradle/eclipse.

You can look at Caffeine's build, which has jmh gradle [support](https://github.com/ben-manes/caffeine/blob/master/gradle/jmh.gradle) and I use Eclipse too. Feel welcome to borrow anything or ask me questions.

**Comment by Speiger** [comment]
eh yeah this confuses me
https://github.com/ben-manes/caffeine/blob/master/gradle/jmh.gradle#L40

**Comment by ben-manes** [comment]
That is to specify the benchmark to run at the command line. Otherwise it has to be set in the task definition to a hardcoded value.

```gradle
./gradlew jmh -PincludePattern=GetPutBenchmark
./gradlew jmh -PincludePattern=ComputeBenchmark
```

Since it is a pattern you could cover multiple matches in a run, e.g.
```
./gradlew jmh -PincludePattern=.*Benchmark
```

I don't think the plugin task had a command-line property to use so I added that one. Otherwise you would need a custom task for each benchmark class. The plugin's sample doesn't show this configured so it runs all benchmarks in the project, which might be pretty slow. Or at least that was my understanding when trying to get it to work.

**Comment by Speiger** [comment]
Ok I had a missconception about Jmh.
I thought you can run it through eclipse directly (my preferred method). But it seems with the Jmh plugin you can only really run it through gradle.
Which isn't a problem. I got the example project running.
Now I am trying to make a custom project that just runs a example script. Lets see how well that works.
If it works out fine then I am going to write a couple benchmarks and let them run through to see how well it runs against other libraries

**Comment by ben-manes** [comment]
If you do it in Eclipse then that's a different thing to wrangle. I believe jmh uses code generation so it is not as easy as invoking a main method due to the preprocessing. You can probably run it in Eclipse via a Gradle task, which is just the same as doing it at shell. Maybe there are easier ways, that worked well enough for me and I didn't think much more about it.

**Comment by Speiger** [comment]
Yeah i got it already running. I got stuck for some time because i couldn't read error logs. 🤦 but yeah i am writing now benchmarks...
Here is the project. Right now bare bones but later there will be more.
https://github.com/Speiger/Primitive-Collections-Benchmarks

By the way again thank you for the extra help ^^"

**Comment by ben-manes** [comment]
oh yeah, I use `--no-daemon` with jmh because there used to be some bugs with the plugin. I think that was https://github.com/melix/jmh-gradle-plugin/issues/170 but not sure anymore. In that mode it might be easier to interrupt.

**Comment by Speiger** [comment]
well gonna do this test i found on Baeldung. I know its a very small one on the other hand its a really good to start with...
Just that it takes half an hour to complete...
https://github.com/Speiger/Primitive-Collections-Benchmarks/blob/master/src/jmh/java/speiger/src/collections/SetAddBenchmark.java
